const esc = value => String(value ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const safeJson = value => JSON.stringify(value).replace(/</g, '\\u003c');

export function renderHtml(model, summary) {
  const data = safeJson(model);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QKTestAnalytics</title>
<style>:root{font-family:Inter,ui-sans-serif,system-ui;color:#172033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1280px;margin:auto;padding:28px}.head{display:flex;justify-content:space-between;gap:16px;align-items:end}.brand{font-weight:800;font-size:26px}.muted{color:#697386}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:24px 0}.card{background:#fff;border:1px solid #e5e9f2;border-radius:14px;padding:16px;box-shadow:0 2px 10px #1720330a}.kpi b{font-size:28px;display:block}.bar{height:8px;background:#edf0f5;border-radius:9px;overflow:hidden;margin-top:8px}.bar i{display:block;height:100%;background:#2d6cdf}.tools{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}input,select{padding:10px 12px;border:1px solid #d8deea;border-radius:9px;background:#fff}.execution{margin:12px 0}summary{cursor:pointer;font-weight:700}.test{border-left:4px solid #aeb7c6;margin:10px 0;padding:10px 12px;background:#fafbfe;border-radius:8px}.PASSED{border-left-color:#35a46f}.FAILED{border-left-color:#d94c4c}.badge{font-size:11px;font-weight:800;padding:3px 7px;border-radius:20px;background:#edf0f5;margin-left:8px}.row{display:flex;justify-content:space-between;gap:12px}.error{white-space:pre-wrap;background:#fff0f0;color:#9f2323;padding:8px;border-radius:7px;font-size:12px}.step{font-size:13px;padding:5px 0;border-top:1px solid #edf0f5}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.head{align-items:start;flex-direction:column}}</style></head><body><main class="wrap"><div class="head"><div><div class="brand">QKTestAnalytics</div><div class="muted">Framework-agnostic test analytics · schema ${esc(model.schemaVersion)}</div></div><div class="muted">Generated ${esc(model.generatedAt)}</div></div>
<section class="grid"><div class="card kpi"><span>Tests</span><b>${summary.tests}</b></div><div class="card kpi"><span>Passed</span><b>${summary.passed}</b></div><div class="card kpi"><span>Failed</span><b>${summary.failed}</b></div><div class="card kpi"><span>Pass rate</span><b>${summary.passRate}%</b><div class="bar"><i style="width:${summary.passRate}%"></i></div></div><div class="card kpi"><span>Executions</span><b>${summary.executions}</b></div></section>
<div class="tools"><input id="q" placeholder="Search tests or suites"><select id="status"><option value="">All statuses</option><option>PASSED</option><option>FAILED</option><option>SKIPPED</option><option>UNKNOWN</option></select><select id="cycle"><option value="">All cycles</option></select></div><section id="results"></section></main>
<script type="application/json" id="qkta-data">${data}</script><script>const data=JSON.parse(document.getElementById('qkta-data').textContent);const r=document.getElementById('results'),q=document.getElementById('q'),s=document.getElementById('status'),c=document.getElementById('cycle');[...new Set(data.executions.map(e=>e.cycle))].forEach(v=>c.add(new Option(v,v)));const e=x=>String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));function render(){const term=q.value.toLowerCase(),status=s.value,cycle=c.value;r.innerHTML=data.executions.filter(x=>!cycle||x.cycle===cycle).map(x=>{const tests=(x.tests||[]).filter(t=>(!status||t.status===status)&&(!term||(t.name+' '+t.suite).toLowerCase().includes(term)));if(!tests.length)return'';return '<details class="card execution" open><summary>'+e(x.project||x.id)+' <span class="badge">'+e(x.cycle)+'</span></summary><div class="muted">'+e(x.startedAt||'')+'</div>'+tests.map(t=>'<div class="test '+e(t.status)+'"><div class="row"><strong>'+e(t.suite)+' · '+e(t.name)+'</strong><span class="badge">'+e(t.status)+'</span></div><div class="muted">'+(t.durationMs/1000).toFixed(2)+'s'+(t.browser?' · '+e(t.browser):'')+'</div>'+(t.error?'<pre class="error">'+e(t.error)+'</pre>':'')+(t.steps||[]).map(st=>'<div class="step">'+e(st.name)+' '+(st.status?'<span class="badge">'+e(st.status)+'</span>':'')+'</div>').join('')+'</div>').join('')+'</details>'}).join('')||'<div class="card muted">No matching tests.</div>'}q.oninput=s.onchange=c.onchange=render;render();</script></body></html>`;
}
